version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: gophermart:dev
    container_name: "gophermart.dev"
    command: /bin/sh -c "go run cmd/gophermart/main.go"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - pkg:/go/pkg
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: "postgres.dev"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
  pkg: