# Fetching the latest golang image on apline linux
FROM golang:1.22-alpine

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copying all the files in our project
COPY . .

# Starting our application
CMD ["go", "run", "cmd/gophermart/main.go"]

# Exposing server port
EXPOSE 8080